ClassDemoRunApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ClassDemoRunApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ClassDemoRunApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ClassDemoRunApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ClassDemoRunApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ClassDemoRunApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ClassDemoRunApp/Pages/runs/Delete.cshtml.cs
using ClassDemoRunApp.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RunLib.model;

namespace ClassDemoRunApp.Pages.runs
{
    public class DeleteModel : PageModel
    {
        private readonly IMedlemRepositoryService service;

        public DeleteModel(IMedlemRepositoryService repo)
        {
            service = repo;
        }


        /*
         * Properties
         */
        public Medlem Medlem { get; set; }

        public void OnGet(int id)
        {
            Medlem = service.GetById(id);
        }

        public IActionResult OnPostSlet(int id)
        {
            service.Delete(id);
            return RedirectToPage("Index");
        }

        public IActionResult OnPostFortryd()
        {
            return RedirectToPage("Index");
        }
    }
}

ClassDemoRunApp/Pages/runs/Index.cshtml.cs
using ClassDemoRunApp.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RunLib.model;

namespace ClassDemoRunApp.Pages.runs
{
    public class IndexModel : PageModel
    {
        private readonly IMedlemRepositoryService service;

        public IndexModel(IMedlemRepositoryService repo)
        {
            service = repo;
        }


        /*
         * Properties for the page
         */
        public List<Medlem> Medlemmer { get; private set; }

        
        public void OnGet()
        {
            Medlemmer = service.GetAll();
        }

    }
}

ClassDemoRunApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ClassDemoRunApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClassDemoRunApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClassDemoRunApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ClassDemoRunApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="runs/Index">Running</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ClassDemoRunApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ClassDemoRunApp/Pages/runs/Create.cshtml
@page
@model ClassDemoRunApp.Pages.runs.CreateModel
@{
}

<h1>Opret en nyt Medlem</h1>

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.Id" class="control-label">Medlems Id</label><br>
                <input asp-for="@Model.Id" class="form-control" /><br>
                <span asp-validation-for="@Model.Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Navn</label><br>
                <input asp-for="@Model.Navn" class="form-control" /><br />
                <span asp-validation-for="@Model.Navn" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Mobil</label><br>
                <input asp-for="@Model.Mobil" class="form-control" /><br />
                <span asp-validation-for="@Model.Mobil" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Hold</label><br>
                <input asp-for="@Model.Hold" class="form-control" /><br />
                @if (!string.IsNullOrEmpty(Model.ErrorHold))
                {
                    <div class="text-danger">@Model.ErrorHold</div>
                }
            </div>

            <div class="form-group">
                <label>Pris</label><br>
                <input asp-for="@Model.Price" class="form-control" /><br />
                <span asp-validation-for="@Model.Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Medlems Type</label><br>
                <select id="Type" name="Type" asp-for="Type" class="form-control">
                    @foreach (var mt in Model.MedlemsTyper)
                    {
                        <option value="@mt">@mt</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <input type="submit" value="Opret Medlem" />
            </div>

        </form>
    </div>
</div>

ClassDemoRunApp/Pages/runs/Delete.cshtml
@page
@model ClassDemoRunApp.Pages.runs.DeleteModel
@{
}
<h1>Vil du slette</h1>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Medlems Id</td>
            <td>@Model.Medlem.MedlemsId</td>
        </tr>
        <tr>
            <td>Medlems Id</td>
            <td>@Model.Medlem.MedlemsId</td>
        </tr>
        <tr>
            <td>Navn</td>
            <td>@Model.Medlem.Navn</td>
        </tr>
        <tr>
            <td>Medlems Mobil</td>
            <td>@Model.Medlem.Mobil</td>
        </tr>
        <tr>
            <td>Medlems LøbeHold</td>
            <td>@Model.Medlem.LøbeHold</td>
        </tr>
    </tbody>
</table>


<form method="post">
    <div class="form-group">
        <input type="submit" value="Slet" asp-page-handler="Slet" asp-route-id="@Model.Medlem.MedlemsId" class="btn btn-danger" />

        <input type="submit" value="Fortryd" asp-page-handler="Fortryd" class="btn btn-primary" />
    </div>
</form>

ClassDemoRunApp/Pages/runs/Edit.cshtml
@page
@model ClassDemoRunApp.Pages.runs.EditModel
@{
}
<h1>Opdater Medlem nummer @Model.Id @Model.Navn</h1>

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div class="form-group">
                <input type="hidden" asp-for="@Model.Id" class="form-control" /><br>
            </div>

            <div class="form-group">
                <label>Navn</label><br>
                <input asp-for="@Model.Navn" class="form-control" /><br />
                <span asp-validation-for="@Model.Navn" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Mobil</label><br>
                <input asp-for="@Model.Mobil" class="form-control" /><br />
                <span asp-validation-for="@Model.Mobil" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Hold</label><br>
                <input asp-for="@Model.Hold" class="form-control" /><br />
                <span asp-validation-for="@Model.Hold" class="text-danger"></span>
                @if (!string.IsNullOrEmpty(Model.ErrorHold))
                {
                    <div class="text-danger">@Model.ErrorHold</div>
                }
            </div>

            <div class="form-group">
                <label>Pris</label><br>
                <input asp-for="@Model.Price" class="form-control" /><br />
                <span asp-validation-for="@Model.Price" class="text-danger"></span>
            </div>

            <form method="post">
                <div class="form-group">
                    <input type="submit" value="Edit" asp-page-handler="Edit" asp-route-id="@Model.Id" class="btn btn-success" />

                    <input type="submit" value="Fortryd" asp-page-handler="Fortryd" class="btn btn-primary" />
                </div>
            </form>

        </form>
    </div>
</div>

ClassDemoRunApp/Pages/runs/Index.cshtml
@page
@model ClassDemoRunApp.Pages.runs.IndexModel
@{
}
<h1>Velkommen til 'Løb for Livet' medlemsoversigt</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>MedlemsId</th>
            <th>Navn</th>
            <th>Mobil</th>
            <th>Hold</th>
            <th>Pris</th>
            <th>Medlems type</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model.Medlemmer)
        {
                <tr>
                    <td>@m.MedlemsId</td>
                    <td>@m.Navn</td>
                    <td>@m.Mobil</td>
                    <td>@m.LøbeHold</td>
                    <td>@m.Pris</td>
                    <td>@m.MedlemsType</td>

                    <td>
                        <a asp-page="Delete" asp-route-id="@m.MedlemsId">Delete</a>
                        |
                        <a asp-page="Edit" asp-route-id="@m.MedlemsId">Edit</a>
                    </td>
                </tr>
        }
    </tbody>
</table>



<form method="get">
    <button class="btn btn-warning" asp-page="Create">Opret Nyt Medlem</button>
</form>